Add options UI and setting for context filtering
totallymike/contextPlus pull request #41
Opened 2018-05-16 18:26 UTC by opes

I wanted to have the ability to filter the list of containers that appear in the context menu (similar to how the [Switch Container Plus](https://github.com/stoically/switch-container-plus) addon does it). This commit adds a basic options UI with a setting to set a regex for filtering the list of containers. Since it saves this setting to storage, the additional `storage` permission is required.

2018-05-16 18:30 UTC, opes commented
@totallymike This may or may not be something you're interested in for this addon. I personally find it a necessity when using other addons that create or manage containers on the fly, such as [Temporary Containers](https://github.com/stoically/temporary-containers).

I realized after committing that [Prettier](https://github.com/prettier/prettier) was set up in my editor to format on save. If the minor style changes are not to your liking, I will gladly remove them.

Thanks for your hard work on this addon!

2018-05-17 16:12 UTC, totallymike requested changes
Thanks for adding this! I'm sure it _will_ come in rather handy. I tested it and it works great.

I think prettier is a great idea. I'd only ask that you add

```javascript
// .prettierrc.js
module.exports = {
  trailingComma: "es5",
};
```

to the project root and resave `contextPlus.js` with the new settings.

After that, I'll merge this and push a new version.

2018-05-17 16:29 UTC, opes commented
@totallymike Done! Thanks again!

2018-05-17 16:30 UTC, totallymike approved these changes
Thanks!

2018-05-17 16:30 UTC, merged